/*
 * This file is the main driver for the Midnight bulletin board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import { webcrypto } from 'crypto';
import {
  type BBoardProviders,
  type PrivateStates,
  BBoardAPI,
  utils,
  type BBoardDerivedState,
  type DeployedBBoardContract,
} from '@midnight-ntwrk/bboard-api';
import { ledger, type Ledger } from '@midnight-ntwrk/bboard-contract';
import {
  type BalancedTransaction,
  createBalancedTx,
  type MidnightProvider,
  type UnbalancedTransaction,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { type Wallet } from '@midnight-ntwrk/wallet-api';
import * as Rx from 'rxjs';
import { firstValueFrom } from 'rxjs';
import { type CoinInfo, nativeToken, Transaction, type TransactionId } from '@midnight-ntwrk/ledger';
import { Transaction as ZswapTransaction } from '@midnight-ntwrk/zswap';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { type Resource, WalletBuilder } from '@midnight-ntwrk/wallet';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import type { StartedDockerComposeEnvironment, DockerComposeEnvironment } from 'testcontainers';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { getLedgerNetworkId, getZswapNetworkId } from '@midnight-ntwrk/midnight-js-network-id';

// @ts-expect-error: It's needed to make Scala.js and WASM code able to use cryptography
globalThis.crypto = webcrypto;
// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getBBoardLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific bulletin board contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the bulletin board contract.
 */
export const getBBoardLedgerState = (
  providers: BBoardProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> =>
  providers.publicDataProvider
    .queryContractState(contractAddress)
    .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */
const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new bulletin board contract
  2. Join an existing bulletin board contract
  3. Exit an existing bulletin board contract
Which would you like to do? `;

const deployOrJoin = async (providers: BBoardProviders, rli: Interface, logger: Logger): Promise<BBoardAPI | null> => {
  let api: BBoardAPI | null = null;
  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        // Fix: Pass undefined as the second parameter and logger as the third parameter
        api = await BBoardAPI.deploy(providers, undefined, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await BBoardAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the bulletin board.
 */
const displayLedgerState = async (
  providers: BBoardProviders,
  deployedBBoardContract: DeployedBBoardContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedBBoardContract.deployTxData.public.contractAddress;
  const ledgerState = await getBBoardLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no passport verification contract deployed at ${contractAddress}`);
  } else {
    logger.info(`Admin address: ${toHex(ledgerState.adminAddress)}`);
    // Fix: Remove reference to userPassportMap which doesn't exist in our Ledger type
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */
const displayPrivateState = async (providers: BBoardProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get('bboardPrivateState');
  if (privateState === null) {
    logger.info(`There is no existing passport verification private state`);
  } else {
    const passportData = privateState.userPassportData;
    logger.info('Current passport data:');
    logger.info(` - Nationality: ${new TextDecoder().decode(passportData.nationality)}`);
    logger.info(` - Date of Birth: ${new Date(Number(passportData.date_of_birth)).toLocaleDateString()}`);
    logger.info(` - Date of Emission: ${new Date(Number(passportData.date_of_emision)).toLocaleDateString()}`);
    logger.info(` - Expiration Date: ${new Date(Number(passportData.expiration_date)).toLocaleDateString()}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the poster key with the private secret key to
 * determine if the current user is the poster of the current message.
 */
const displayDerivedState = (ledgerState: BBoardDerivedState | undefined, logger: Logger) => {
  if (ledgerState === undefined) {
    logger.info(`No passport verification state currently available`);
  } else {
    logger.info(`Admin address: ${toHex(ledgerState.adminAddress)}`);
    // Fix: Remove reference to userPassportMap which doesn't exist in BBoardDerivedState
    const passportData = ledgerState.passport_data;
    logger.info('Current passport data:');
    logger.info(` - Nationality: ${new TextDecoder().decode(passportData.nationality)}`);
    logger.info(` - Date of Birth: ${new Date(Number(passportData.date_of_birth)).toLocaleDateString()}`);
    logger.info(` - Date of Emission: ${new Date(Number(passportData.date_of_emision)).toLocaleDateString()}`);
    logger.info(` - Expiration Date: ${new Date(Number(passportData.expiration_date)).toLocaleDateString()}`);
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the bulletin board CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */
const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Register user with passport
  2. Verify nationality (Argentine)
  3. Verify age (18+)
  4. Verify passport expiration
  5. Display the current ledger state (known by everyone)
  6. Display the current private state (known only to this DApp instance)
  7. Display the current derived state (known only to this DApp instance)
  8. Exit
Which would you like to do? `;

const help = async (logger: Logger): Promise<void> => {
  logger.info('Available commands:');
  logger.info('  deploy - Deploy a new bulletin board contract');
  logger.info('  join <contract_address> - Join an existing bulletin board contract');
  logger.info('  validate_nationality - Check if user is Argentine');
  logger.info('  validate_adulthood - Check if user is over 18');
  logger.info('  passport_is_unexpired - Check if passport is not expired');
  logger.info('  help - Print this help message');
  logger.info('  exit - Exit the program');
};

// Variable to store the currently deployed API
let deployedBBoardAPI: BBoardAPI | null = null;

const mainLoop = async (providers: BBoardProviders, rli: Interface, logger: Logger): Promise<void> => {
  const bboardApi = await deployOrJoin(providers, rli, logger);
  if (bboardApi === null) {
    return;
  }

  let currentState: BBoardDerivedState | undefined;
  const stateObserver = {
    next: (state: BBoardDerivedState) => (currentState = state),
  };
  const subscription = bboardApi.state$.subscribe(stateObserver);

  const commands: Record<string, (args: string[], logger: Logger) => Promise<void>> = {
    deploy: async (_, logger) => deploy(providers, logger),
    join: async (args, logger) => {
      // ...existing code...
    },
    validate_nationality: async (_, logger) => {
      // ...existing code...
    },
    validate_adulthood: async (_, logger) => {
      // ...existing code...
    },
    passport_is_unexpired: async (_, logger) => {
      // ...existing code...
    },
    help: async (_, logger) => help(logger),
    exit: async () => {
      // ...existing code...
    },
  };
  
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      switch (choice) {
        case '1':
          logger.info('Registering user with passport data...');
          await displayPrivateState(providers, logger);
          break;
        case '2':
          logger.info('Verifying nationality...');
          await bboardApi.validate_nationality();
          break;
        case '3':
          logger.info('Verifying age...');
          await bboardApi.validate_adulthood();
          break;
        case '4':
          logger.info('Verifying passport expiration...');
          await bboardApi.passport_is_unexpired();
          break;
        case '5':
          await displayLedgerState(providers, bboardApi.deployedContract, logger);
          break;
        case '6':
          await displayPrivateState(providers, logger);
          break;
        case '7':
          displayDerivedState(currentState, logger);
          break;
        case '8':
          logger.info('Exiting...');
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    }
  } finally {
    subscription.unsubscribe();
  }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */
const createWalletAndMidnightProvider = async (wallet: Wallet): Promise<WalletProvider & MidnightProvider> => {
  const state = await Rx.firstValueFrom(wallet.state());
  return {
    coinPublicKey: state.coinPublicKey,
    balanceTx(tx: UnbalancedTransaction, newCoins: CoinInfo[]): Promise<BalancedTransaction> {
      return wallet
        .balanceTransaction(
          ZswapTransaction.deserialize(tx.serialize(getLedgerNetworkId()), getZswapNetworkId()),
          newCoins,
        )
        .then((tx) => wallet.proveTransaction(tx))
        .then((zswapTx) => Transaction.deserialize(zswapTx.serialize(getZswapNetworkId()), getLedgerNetworkId()))
        .then(createBalancedTx);
    },
    submitTx(tx: BalancedTransaction): Promise<TransactionId> {
      return wallet.submitTransaction(tx);
    },
  };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */
const waitForFunds = (wallet: Wallet, logger: Logger) =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.tap((state) => {
        const scanned = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total.toString() ?? 'unknown number';
        logger.info(`Wallet processed ${scanned} indices out of ${total}`);
      }),
      Rx.filter((state) => {
        // Let's allow progress only if wallet is close enough
        const synced = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total ?? 1_000n;
        return total - synced < 100n;
      }),
      Rx.map((s) => s.balances[nativeToken()] ?? 0n),
      Rx.filter((balance) => balance > 0n),
    ),
  );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */
const buildWalletAndWaitForFunds = async (
  { indexer, indexerWS, node, proofServer }: Config,
  logger: Logger,
  seed: string,
): Promise<Wallet & Resource> => {
  const wallet = await WalletBuilder.buildFromSeed(
    indexer,
    indexerWS,
    proofServer,
    node,
    seed,
    getZswapNetworkId(),
    'warn',
  );
  wallet.start();
  const state = await Rx.firstValueFrom(wallet.state());
  logger.info(`Your wallet seed is: ${seed}`);
  logger.info(`Your wallet address is: ${state.address}`);
  
  let balance = state.balances[nativeToken()];
  if (balance === undefined || balance === 0n) {
    logger.info(`Your wallet balance is: 0`);
    logger.info(`Waiting to receive tokens...`);
    balance = await waitForFunds(wallet, logger);
  }
  logger.info(`Your wallet balance is: ${balance}`);
  return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (config: Config, logger: Logger): Promise<Wallet & Resource> =>
  await buildWalletAndWaitForFunds(config, logger, toHex(utils.randomBytes(32)));

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (config: Config, rli: Interface, logger: Logger): Promise<Wallet & Resource> => {
  const seed = await rli.question('Enter your wallet seed: ');
  return await buildWalletAndWaitForFunds(config, logger, seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* *******************************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */
const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<(Wallet & Resource) | null> => {
  if (config instanceof StandaloneConfig) {
    return await buildWalletAndWaitForFunds(config, logger, GENESIS_MINT_WALLET_SEED);
  }
  
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return await buildFreshWallet(config, logger);
      case '2':
        return await buildWalletFromSeed(config, rli, logger);
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

const mapContainerPort = (env: StartedDockerComposeEnvironment, url: string, containerName: string) => {
  const mappedUrl = new URL(url);
  const container = env.getContainer(containerName);
  mappedUrl.port = String(container.getFirstMappedPort());
  return mappedUrl.toString().replace(/\/+$/, '');
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */
export const run = async (config: Config, logger: Logger, dockerEnv?: DockerComposeEnvironment): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  let env;
  
  try {
    if (dockerEnv !== undefined) {
      env = await dockerEnv.up();
      
      if (config instanceof StandaloneConfig) {
        config.indexer = mapContainerPort(env, config.indexer, 'bboard-indexer');
        config.indexerWS = mapContainerPort(env, config.indexerWS, 'bboard-indexer');
        config.node = mapContainerPort(env, config.node, 'bboard-node');
        config.proofServer = mapContainerPort(env, config.proofServer, 'bboard-proof-server');
      }
    }
    
    const wallet = await buildWallet(config, rli, logger);
    
    try {
      if (wallet !== null) {
        const walletAndMidnightProvider = await createWalletAndMidnightProvider(wallet);
        const providers = {
          privateStateProvider: levelPrivateStateProvider<PrivateStates>({
            privateStateStoreName: config.privateStateStoreName,
          }),
          publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
          zkConfigProvider: new NodeZkConfigProvider<'validate_nationality' | 'validate_adulthood' | 'passport_is_unexpired'>(config.zkConfigPath),
          proofProvider: httpClientProofProvider(config.proofServer),
          walletProvider: walletAndMidnightProvider,
          midnightProvider: walletAndMidnightProvider,
        };
        
        await mainLoop(providers, rli, logger);
      }
    } catch (e) {
      if (e instanceof Error) {
        logger.error(`Found error '${e.message}'`);
        logger.info('Exiting...');
        logger.debug(`${e.stack}`);
      } else {
        throw e;
      }
    } finally {
      if (wallet !== null) {
        await wallet.close();
      }
    }
  } catch (e) {
    logger.error(e instanceof Error ? e.message : String(e));
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      // Ignore errors when closing readline interface
    } finally {
      if (env !== undefined) {
        try {
          await env.down();
          logger.info('Goodbye');
        } catch (e) {
          // Ignore errors when shutting down Docker
        } finally {
          process.exit(0);
        }
      }
    }
  }
};

// Helper functions
const deploy = async (providers: BBoardProviders, logger: Logger): Promise<void> => {
  logger.info('Deploying a bulletin board...');
  try {
    // Fix: Pass undefined as the second parameter (consistent with the earlier fix)
    const api = await BBoardAPI.deploy(providers, undefined, logger);
    logger.info(`Deployed bulletin board contract at ${api.deployedContractAddress}`);
    
    // Log passport data information
    const state = await firstValueFrom(api.state$);
    logger.info(`Contract deployed with passport data for nationality: ${new TextDecoder().decode(state.passport_data.nationality)}`);
    
    // Store it for later
    deployedBBoardAPI = api;
  } catch (error: unknown) {
    logger.error(error, 'Failed to deploy bulletin board');
  }
};

const join = async (contractAddress: string, providers: BBoardProviders, logger: Logger): Promise<void> => {
  logger.info(`Joining bulletin board contract at ${contractAddress}`);
  try {
    const api = await BBoardAPI.join(providers, contractAddress, logger);
    
    // Log passport data information
    const state = await firstValueFrom(api.state$);
    logger.info(`Contract contains passport data for nationality: ${new TextDecoder().decode(state.passport_data.nationality)}`);
    
    // Store it for later
    deployedBBoardAPI = api;
  } catch (error: unknown) {
    logger.error(error, 'Failed to join bulletin board');
  }
};
