/**
 * Provides utility functions.
 *
 * @module
 */
import { PassportDataPacket } from '../../../contract/src/managed/bboard/contract/index.cjs';

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

// export const dummyPassportData = (): PassportDataPacket => {
//   const bytes : PassportDataPacket = 
//   return bytes;
// };